=== oscarvazfalagan/Codigo/Lima/XML/UD_4/ACT_1/defFaq.dtd
<!ELEMENT FAQ (INFO, PART+)>
<!ELEMENT INFO (TITULO, AUTOR, EMAIL, VERSION, FECHA)>
<!ELEMENT PART (Q+)>
<!ELEMENT Q (QTEXT, A)>
<!ELEMENT TITULO (#PCDATA)>
<!ELEMENT AUTOR (#PCDATA) >
<!ELEMENT EMAIL (#PCDATA) >
<!ELEMENT VERSION (#PCDATA) >
<!ELEMENT FECHA (#PCDATA) >

<!ATTLIST PART number CDATA #REQUIRED>
<!ATTLIST Q id CDATA #REQUIRED>
<!ELEMENT QTEXT (#PCDATA) >
<!ELEMENT A (#PCDATA) >

=== oscarvazfalagan/Codigo/Lima/XML/UD_4/ACT_1/ej_8.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE FAQ SYSTEM "defFaq.dtd">
<FAQ>
    <INFO>
        <TITULO> WINDOWS98? SOLO SI ME OBLIGAN! </TITULO>
        <AUTOR> Fernando Damián Lorenzo García </AUTOR>
        <EMAIL> Fer@yahoo.es </EMAIL>
        <VERSION> 1.0 </VERSION>
        <FECHA> 20.MAYO.99 </FECHA>
    </INFO>
    <PART number="P1">
        <Q id="Q1">
            <QTEXT>¿Por qué tengo que instalar W95?</QTEXT>
            <A> A mi también me parece una buena pregunta.</A>
        </Q>
        <Q id="Q2">
            <QTEXT>Y de que me vale?</QTEXT>
            <A>Otra ingeniosa pregunta.</A>
        </Q>
    </PART>
</FAQ>
