=== oscarvazfalagan/Codigo/Lima/XML/UD_4/ACT_1/defPersonas.dtd
<!ELEMENT nombre (#PCDATA) >
<!ELEMENT fecnac (#PCDATA) >
<!ELEMENT sexo (#PCDATA) >
<!ELEMENT numss (#PCDATA)>
<!ELEMENT telefono (#PCDATA) >
<!ELEMENT lista_de_personas (persona+)>
<!ELEMENT persona (nombre,fecnac,telefono+,sexo?,numss?)>
<!ELEMENT nacionalidad (#PCDATA)>
<!ATTLIST persona nacionalidad CDATA #REQUIRED>

=== oscarvazfalagan/Codigo/Lima/XML/UD_4/ACT_1/miPersonas.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE lista_de_personas SYSTEM "defPersonas.dtd">
<lista_de_personas>
    <persona nacionalidad="español">
        <nombre>José García</nombre>
        <fecnac>25/04/1984</fecnac>
        <telefono>670201256</telefono>
        <telefono>968472898</telefono>
        <sexo>Varón</sexo>
    </persona>
    <persona nacionalidad="español">
        <nombre>Juan Antonio</nombre>
        <fecnac>25/04/1984</fecnac>
        <telefono>670201256</telefono>
        <numss>2569587412569</numss>
    </persona>
</lista_de_personas>
